name: rational
version: 0.1.4
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to deal with rational numbers
homepage: https://github.com/a14n/dart-rational
dev_dependencies:
  browser: ">=0.9.0 <0.10.0"
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"